// <auto-generated />
using System;
using KRCP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KRCP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903232817_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KRCP.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("CategoriaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("KRCP.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<string>("ContactoEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ContactoEmail");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("RUC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("RUC");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("RazonSocial");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono");

                    b.HasKey("ClienteId");

                    b.HasIndex("RUC")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("KRCP.Domain.Entities.ErpIntegracionLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Accion");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EntidadAfectada");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int")
                        .HasColumnName("EntidadID");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FechaRegistro")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("varchar(MAX)")
                        .HasColumnName("PayloadJSON");

                    b.HasKey("LogId");

                    b.ToTable("ERP_IntegracionLog", (string)null);
                });

            modelBuilder.Entity("KRCP.Domain.Entities.MovimientoKardex", b =>
                {
                    b.Property<int>("KardexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KardexID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KardexId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<DateTime>("FechaMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FechaMovimiento")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Motivo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Motivo");

                    b.Property<int?>("OtId")
                        .HasColumnType("int")
                        .HasColumnName("OTID");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    b.Property<int>("StockAnterior")
                        .HasColumnType("int")
                        .HasColumnName("StockAnterior");

                    b.Property<int>("StockNuevo")
                        .HasColumnType("int")
                        .HasColumnName("StockNuevo");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TipoMovimiento");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("KardexId");

                    b.HasIndex("OtId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientosKardex", (string)null);
                });

            modelBuilder.Entity("KRCP.Domain.Entities.OrdenTrabajo", b =>
                {
                    b.Property<int>("OtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OTID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    b.Property<string>("CodigoOT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CodigoOT");

                    b.Property<decimal>("CostoManoObra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("CostoManoObra");

                    b.Property<decimal>("CostoRepuestos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("CostoRepuestos");

                    b.Property<decimal>("CostoTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("CostoTotal");

                    b.Property<string>("EquipoComponente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EquipoComponente");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Registrado")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCierre");

                    b.Property<DateTime?>("FechaEstimadaEntrega")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaEstimadaEntrega");

                    b.Property<DateTime>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FechaIngreso")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NumeroSerie");

                    b.Property<string>("Observaciones")
                        .HasColumnType("varchar(MAX)")
                        .HasColumnName("Observaciones");

                    b.Property<int?>("TecnicoAsignadoId")
                        .HasColumnType("int")
                        .HasColumnName("TecnicoAsignadoID");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioModificacionID");

                    b.Property<int>("UsuarioPlanificadorId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioPlanificadorID");

                    b.HasKey("OtId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CodigoOT")
                        .IsUnique();

                    b.HasIndex("TecnicoAsignadoId");

                    b.HasIndex("UsuarioModificacionId");

                    b.HasIndex("UsuarioPlanificadorId");

                    b.ToTable("OrdenesTrabajo", (string)null);
                });

            modelBuilder.Entity("KRCP.Domain.Entities.OtEvidencia", b =>
                {
                    b.Property<int>("EvidenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EvidenciaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvidenciaId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Descripcion");

                    b.Property<DateTime>("FechaCarga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCarga")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("OtId")
                        .HasColumnType("int")
                        .HasColumnName("OTID");

                    b.Property<string>("TipoEvidencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TipoEvidencia");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("UrlArchivo");

                    b.Property<int>("UsuarioCargaId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioCargaID");

                    b.HasKey("EvidenciaId");

                    b.HasIndex("OtId");

                    b.HasIndex("UsuarioCargaId");

                    b.ToTable("OT_Evidencias", (string)null);
                });

            modelBuilder.Entity("KRCP.Domain.Entities.OtRepuestoConsumido", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DetalleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<DateTime>("FechaDespacho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FechaDespacho")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("OtId")
                        .HasColumnType("int")
                        .HasColumnName("OTID");

                    b.Property<decimal>("PrecioUnitarioHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("PrecioUnitarioHistorico");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    b.Property<int>("UsuarioAlmacenId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioAlmacenID");

                    b.HasKey("DetalleId");

                    b.HasIndex("OtId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioAlmacenId");

                    b.ToTable("OT_RepuestosConsumidos", (string)null);
                });

            modelBuilder.Entity("KRCP.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    b.Property<string>("CodigoParte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoParte");

                    b.Property<decimal>("CostoUnitario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("CostoUnitario");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nombre");

                    b.Property<int>("StockActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("StockActual");

                    b.Property<int>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5)
                        .HasColumnName("StockMinimo");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("int")
                        .HasColumnName("UbicacionID");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioModificacionID");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoParte")
                        .IsUnique();

                    b.HasIndex("UbicacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("KRCP.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreRol");

                    b.HasKey("RolId");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("KRCP.Domain.Entities.Ubicacion", b =>
                {
                    b.Property<int>("UbicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UbicacionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UbicacionId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<string>("CodigoUbicacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoUbicacion");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Descripcion");

                    b.HasKey("UbicacionId");

                    b.HasIndex("CodigoUbicacion")
                        .IsUnique();

                    b.ToTable("Ubicaciones", (string)null);
                });

            modelBuilder.Entity("KRCP.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PasswordHash");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("KRCP.Domain.Entities.MovimientoKardex", b =>
                {
                    b.HasOne("KRCP.Domain.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany()
                        .HasForeignKey("OtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KRCP.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KRCP.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KRCP.Domain.Entities.OrdenTrabajo", b =>
                {
                    b.HasOne("KRCP.Domain.Entities.Cliente", "Cliente")
                        .WithMany("OrdenesTrabajo")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KRCP.Domain.Entities.Usuario", "TecnicoAsignado")
                        .WithMany()
                        .HasForeignKey("TecnicoAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KRCP.Domain.Entities.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KRCP.Domain.Entities.Usuario", "UsuarioPlanificador")
                        .WithMany()
                        .HasForeignKey("UsuarioPlanificadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("TecnicoAsignado");

                    b.Navigation("UsuarioModificacion");

                    b.Navigation("UsuarioPlanificador");
                });

            modelBuilder.Entity("KRCP.Domain.Entities.OtEvidencia", b =>
                {
                    b.HasOne("KRCP.Domain.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany()
                        .HasForeignKey("OtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KRCP.Domain.Entities.Usuario", "UsuarioCarga")
                        .WithMany()
                        .HasForeignKey("UsuarioCargaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("UsuarioCarga");
                });

            modelBuilder.Entity("KRCP.Domain.Entities.OtRepuestoConsumido", b =>
                {
                    b.HasOne("KRCP.Domain.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany()
                        .HasForeignKey("OtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KRCP.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KRCP.Domain.Entities.Usuario", "UsuarioAlmacen")
                        .WithMany()
                        .HasForeignKey("UsuarioAlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("Producto");

                    b.Navigation("UsuarioAlmacen");
                });

            modelBuilder.Entity("KRCP.Domain.Entities.Producto", b =>
                {
                    b.HasOne("KRCP.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KRCP.Domain.Entities.Ubicacion", "Ubicacion")
                        .WithMany("Productos")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KRCP.Domain.Entities.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Ubicacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("KRCP.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("KRCP.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("KRCP.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("OrdenesTrabajo");
                });

            modelBuilder.Entity("KRCP.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("KRCP.Domain.Entities.Ubicacion", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
